sudo: false
language:
  - node_js
node_js:
  - v4.3.1
  - v5.9.1
install:
  - npm install
script:
  - make test-$TEST_SUITE
env:
  matrix:
  - CC=clang CXX=clang++ npm_config_clang=1 TEST_SUITE=unit
cache:
  directories:
    - node_modules
